### PR TITLE
support for symfony4

### PR DESCRIPTION
**Pull request by Kronhyx**

### CODE REVIEW

**Comment by mhetru** [comment]
thanks for your PR, but i wish verify and test symfony 4.0.
but how have you installed symfony 4.0?

i have test this : https://www.jdecool.fr/blog/2017/09/13/tutorial-jobeet-symfony-4-partie-1-demarrage-projet.html
but symfony 4 has totally changed, whereis the config.yml and parameters.yml?

**Comment by mhetru** [comment]
i have pushed a version for sf 4.0 but i am blocked with this message :
"Container extension "security" is not registered"

**Comment by mhetru** [comment]
i have resolved this error but i am blocked on use with config/packages/security.yaml with this error :
"parent definition l3_firewall in L3\CasBundle\Security\CasProvider does not exist"

**Comment by mhetru** [comment]
i have released a version of the bundle for symfony 4.0.
have fun!
you can close here ;)

**Comment by Kronhyx** [comment]
@mhetru... Sorry for taking so long to respond, everything about symfony4 or 4.2 has been established?

**Comment by mhetru** [comment]
Tested successfully on sf4.1. But sf4.2 cannot get (with composer) at this time

**Comment by Kronhyx** [comment]
@mhetru ... What is the specific problem with symfony4.2 or composer.....  What's wrong with composer?
i can help!

**Comment by mhetru** [comment]
I have successfully tested on sf4.2... i have find the command for get symfony 4.2 :
> composer create-project symfony/website-skeleton test42
It get the last version 4.2.0.2...

I had an error message if i specified the version :
> composer create-project symfony/website test42 4.2

**Pull request closed without merging**
